import type { NextPage } from "next";
import Head from "next/head";
import Main from "../components/Main";
import styles from "../styles/Header.module.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Carouse from "../components/Carouse";
import SubCarousel from "../components/SubCarousel";
import Courses from "../components/Courses";
import Footer from "../components/Footer";
import Header from "../components/Header";
import RegistrationModal from "../components/RegistrationModal";
import { useState } from "react";
import { signIn, getCsrfToken, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState(false);
  const { data } = useSession();
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header {...{ setIsOpen, isOpen, data }} />
      <RegistrationModal {...{ isOpen, setIsOpen, data }} />
      <Carouse />
      <Main />
      <SubCarousel />
      <Courses />
      <Footer />
    </div>
  );
};

export default Home;

export async function getServerSideProps(context: any) {
  return {
    props: {
      csrfToken: await getCsrfToken(context),
    },
  };
}
