import type { NextPage } from "next";
import Head from "next/head";
import Form from "../components/Form";
import { useGetUsersQuery } from "../store/users";
import styles from "../styles/Header.module.scss";

const Home: NextPage = () => {
  const fetchUsers = useGetUsersQuery();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {fetchUsers.isLoading && "Loading"}
      {fetchUsers.data?.map((user) => (
        <h2 className={`${styles.cl} font-header -ml-10`} key={user.id}>
          {user.name}
        </h2>
      ))}

      <div className="m-7 bg-gray-300 p-5 rounded-lg w-56">
        <Form />
      </div>
      <div className="flex border-2 box-border rounded-full overflow-hidden ">
        <div className="bg-slate-500 first-letter:bg-green-300 w-7">Hello</div>
        <div className="bg-slate-500 first-letter:bg-green-500 w-5">Hello</div>
        <div className="bg-slate-500 first-letter:font-bold w-36">Hello</div>
      </div>
    </div>
  );
};

export default Home;
